### ISSUE TITLE
A server restart persistent version of /ClaimExplosions

### ISSUE THREAD

**Issue by Kamology** [ShaneBeee/GriefPreventionFlags#104]
### Description
Pretty self explanatory, simply a flag that functions identical to /ClaimExplosions allowing explosions within a claim, but one that does not get disabled upon server restart. I have a large claim I'd like to have explosions always enabled on but unfortunately can't because of the lack of persistence with the existing /ClaimExplosions, toggling it back off every night with our daily restart. 

If you're able to implement this I'd appreciate it a ton, only thing more I need from GP. Thanks your time and work.

**Comment by ShaneBeee** [comment]
I recommend suggesting this to GP first. 
The reason being is GP would be preventing this, and that command from GP would therefor allow the explosions.
Its not exactly easy to override what another plugin is blocking.

**Comment by Kamology** [comment]
Ah, way ahead o ya lol https://github.com/TechFortress/GriefPrevention/issues/860

If you think it's too difficult to implement it's all good, I'm not too versed on plugin dev or how GP/GP Flags would interact so I wasn't sure if it'd be as easy as just overriding with like an "allow explosions" magic line of code or something.

**Comment by ShaneBeee** [comment]
Ok, sorry its been so long when looking into this.
I did some digging and here is what I found out.

When an entity explodes (ie: creeper/tnt), GriefPrevention modifies the block list, removing blocks from it that shouldn't explode, giving the effect that the explosion did not destroy any blocks.

Due to this, I am not able to modify the list after GP has already done so, since GP has removed the blocks from the list.

In this case, GP would most likely have to create an event, for when its blocking explosions, that I would be able to list to and cancel.
