### ISSUE TITLE
[bug](minor) EnterPVP message not updated on plugin reload [4.13.0]

### ISSUE THREAD

**Issue by arboriginal** [ShaneBeee/GriefPreventionFlags#15]
When entering a PVP area (flag +allowPVP) and set "Send Message On Enter PvP Enabled Claim: true", the message is well sent to player.

But, when editing the parameter in config.yml then use `/gpfreload`, the message is not updated.

**Comment by ShaneBeee** [comment]
confirmed this is not working.
I will take a look at that and make sure the GPFreload reflects that.

**Comment by ShaneBeee** [comment]
Okay, I have no clue what is going on here.
It is set up so it SHOULD reload, but for some silly reason it won't reload to config options.

For now, I will be putting this on hold, since I cant figure out how the heck to get it to work.
For the time being, you will just have to reload/restart your server for those changes to take effect.
