### ISSUE TITLE
Players keep flight when switching claims

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#26]
Players who are trusted in a claim keep flight, even after being untrusted

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
Okay so this one I don't really know how to explain.
In a way it's NOT a GPFlags issue, since the trust stuff is done in GP

BUT... at the same time, This kind of is an issue with GPFlags, if you remove a player from your trust list they can still fly.
Now the good news, is if you remove someone from trust, the can only fly whilst they stay in your claim. The second they leave their flight is removed. 

I don't want to ignore this one, but at the same time I really don't know how to fix it. 
I don't think I have a way to detect when a player gains/loses trust, so I really don't see how I can intercept this. 

For now Im going to label this as `not a GPFlags issue` but I will leave it open and see if I can find a way to fix it.

**Comment by ShaneBeee** [comment]
Okay I just re-read this one
Your title and description don't match.
The title says `Players keep flight when switching claims`
Whereas the description says `Players who are trusted in a claim keep flight, even after being untrusted`

So... I fixed the issue regarding the title.
#### Issue:
When flying in my own claim, if I TP to another persons claim (even if I do not have permission to fly) I was able to fly

#### Fix:
I changed it now to check if the player has permission to fly in that claim. Now removing flight when a player is not trusted in said claim.

**Comment by OpalMoonstride** [comment]
Lol. Sorry about that. Thanks for fixing it! :D

**Comment by ShaneBeee** [comment]
You're welcome
Thats been the hardest one for me to fix so far, haha!
