### ISSUE TITLE
Monsters appear in nomonsterspawns flagged claim

### ISSUE THREAD

**Issue by OpalMoonstride** [ShaneBeee/GriefPreventionFlags#29]
I'm not sure if this is GPflags, or GP, but mobs will appear to spawn in region with the nomonsterspawns flag, and then disappear when walking up to them. This is particularly strange when you're shot once, and then a skeleton disappears, or when a spider appears, and leaves webs behind. I'm not sure if you can fix that, or not. As of right now I'm using GP exclusively for protection, no WorldGuard.

Paper SPigot 1.13.2
GPFlags 4.16.1
GP 16.11.5

**Comment by ShaneBeee** [comment]
This would be frustrating for sure.
I have never experienced anything like this. 

When this is happening, are the mobs spawning naturally or are you using a command or spawn egg to spawn the mob?

**Comment by ShaneBeee** [comment]
It very well could be an issue with MM.

The mobs that are spawning, what are the vanilla types of them?
If they aren't vanilla monsters I can totally see why they are spawning.
If they ARE vanilla monsters, they SHOULDN'T be spawning.

**Comment by ShaneBeee** [comment]
Part 2 of my response.
I did some reading over the code as well as testing.
Here is what happens.

It appears entities can NOT spawn in claims. I can't even use Minecraft's summon command.... just tells me no. 
But what I did notice, if I spawned a zombie near my claim and it was able to come in. But then it would disappear.
Looking over the code it was written so when an entity that is spawned outside of the claim, targets a player in the claim, that entity will be removed, preventing it from entering the claim to kill you.

SO... at the end of the day I can mark this as Not an issue, since it was intentionally written that way, and I dont want to remove that since technically it is not a bug.

**Comment by OpalMoonstride** [comment]
> > I'm wondering if you would be willing to add a timer check for mobs? Maybe like this one? https://gist.github.com/wispoffates/40ae684278bbb3d730c872015094fcb8
> > I had it previously, without performance loss.
> 
> OOF no sorry I will not loop ALL the loaded entities in a world.
Lol I gotcha. Funny irony, though as that's code from Towny. 

Maybe something is forcing my spawns, as they're spawning in the middle of a 1000x1000 claim, so can't be walking in. I'll give it some more testing. Thanks for the consideration!

**Comment by ShaneBeee** [comment]
Yeah my guess is something is forcing the spawns for sure. 
But at least they are disappearing when they spot you.
