### ISSUE TITLE
[Suggested] some flags

### ISSUE THREAD

**Issue by kotarobo** [ShaneBeee/GriefPreventionFlags#38]
Can I add the following flags?
NoIceMelt: Prevents the ice from melting
NoSnowMelt: Prevents the snow from melting
NoWaterBreak: Prevents the carpet and red stone circuit from breaking with water
NoTrampling (NoFarmlandBreak): I proposed it because it could not prevent the player from destroying it.
AllowCrops: Allow crop harvesting.
AllowTreeFarm: If it is to protect plantations. You can plant vines and logs and plant seedlings.

WorldGuard is no longer compatible with other plugins and is very buggy.
You need this feature to get rid of it, so it helps if you think about it.

**Comment by ShaneBeee** [comment]
Hey thanks for the suggestions.
Ill give some feedback on these ideas, as we need to talk about some of these a little more.

NoIceMelt/NoSnowMelt: I like this idea, but I do fear that it could lag a server quite a bit. Ex, lets say you place a torch in the middle of your claim that is covered in snow. The server is going to constantly be trying to melt this snow, but this plugin would be cancelling that event. This would just keep happening, over and over, the more players doing this, with more torches, could possibly lag the server a lot. If I did add this flag, I would definitely have to warn people of its potential lag.

NoWaterBreak: Im not entirely sure how useless this flag would be, since it wouldn't be often you would be pouring water out near these blocks, but I do feel this could be handy once in a while.

AllowCrops: I don't think this is something I would add. You can already give permissions to players via GP to do different things in your claim, and I believe its kind of hard to override what GP is blocking. So if GP is blocking harvesting, it might be difficult to unblock it. I will look into this one a bit more.

AllowTreeFarm: This falls under the same as crops, I will look into it a bit more.

**Comment by ShaneBeee** [comment]
I looked into this a bit more, and I don't think Ill be adding any of these flags

No ice/snow melt: This could be very dangerous and super laggy for a server, that being said I do not feel comfortable adding this into this plugin. This may be something you will have to look into having custom built for your server.

No water break: This seems more like a player accident than a real issue. If players place water and it breaks carpets/redstone, that's their own fault, I don't think a plugin should have to handle taking care of player mistakes.

Allow crops/Tree farm: as previously stated, you can give trust to players in your claims already.

No Trample: I may add this in the future, but again this falls under player mistake. Players whom are not trusted can't trample crops as far as I know (GP prevention), as for the members of the claim, again this falls under player mistake.
