### ISSUE TITLE
Trident with loyalty dissapears when hit mobs in a nomonsterspawns flagged claim

### ISSUE THREAD

**Issue by DmitryRendov** [ShaneBeee/GriefPreventionFlags#57]
### Description
subj reported from my players. sorry didnt check on my own

### Steps to Reproduce
https://youtu.be/2f4a42kSfxE

### Server Information
* **Server version/platform:**        git-Paper-160 (MC: 1.14.4)
* **GriefPrevention Version:**        16.11.5
* **GriefPreventionFlags Version:**   5.5.2

**Comment by ShaneBeee** [comment]
Try on the latest version of the plugin, and see if it's still doing that.

**Comment by DmitryRendov** [comment]
Looks better with 5.5.3 in case of mobs (eg skeleton horse), but trident is still disappearing in case of players attack. will double check if it's not another plugin issue (pvp protection).

**Comment by ShaneBeee** [comment]
Ill take a look into it, I know a lot of plugins have been having issues with Tridents, they're no fun to work with.

**Comment by ShaneBeee** [comment]
[GriefPreventionFlags.jar.zip](https://github.com/ShaneBeee/GriefPreventionFlags/files/3490382/GriefPreventionFlags.jar.zip)
give this version a try at let me know if it works (sorry its a zip file, GitHub won't let me upload a jar) 
I think the issue was I was cancelling all damage by entities, and not checking if said entity was an instance of a living entity

**Comment by DmitryRendov** [comment]
Can confirm, the issue has gone. Big thanks, @ShaneBeee 
it can be closed.
